### ISSUE TITLE
Keep timer running even when window isn't at focus

### ISSUE THREAD

**Issue by SharbelOkzan** [szymmis/coding-timer#1]
Is it possible to keep the timer running even when the window (VScode) isn't focused?
or even better, to have that as an option in extension settings.

Because some people, or me at least, are using the extension to measure time spent working, and needless to say, reading code, using the terminal, or searching something in a browser is also part of the "work" 😄

**Comment by szymmis** [comment]
Hi @SharbelOkzan. It is absolutely possible to develop a feature to be able to keep the counter running even when you are tabbed out. I think that making this feature as a option is a great idea. If you are still interested let me know!

**Comment by SharbelOkzan** [comment]
Hi @szymmis , thanks for the response. Yes, I'm still interested in adding this feature.
My experience is mainly in Flutter, so I'm not sure how much I can help in this TS project, but I'll try to familiarize myself with the language and VSCode API and get back to you for your guidance and review, I think this could be a good first contribution on github for me.

**Comment by szymmis** [comment]
Thank you for your response @SharbelOkzan! If you would like to learn ts and write this feature yourself, go ahead! I'd be delighted if you did, and you can be sure that I'll help you as much as I can.

**Comment by SharbelOkzan** [comment]
Thank you so much @szymmis for the support! 
I will start on it this weekend, 
it may take a long time since it'll be a side project for weekends and involves learning many new things, but I'll definitely enjoy it.
Will get back to you soon, thanks again!

**Comment by SharbelOkzan** [comment]
Hi @szymmis, I've created this [pr](https://github.com/szymmis/coding-timer/pull/2).

I didn't install TypeScript, thus, didn't test the code, so I want to apologize in advance if it isn't compilable.
I figured that installing and configuring TS and learning how get dependencies like the vscode module could take me a long time, but thanks to your very clean code it was easy to make the required changes on the fly in github live editor.

Hope it works 🤞 and waiting for your comments

**Comment by szymmis** [comment]
Hello again @SharbelOkzan! It is quite impressive how well you managed to find yourself in a foreign codebase in a language you don't write in. There is only one small syntax mistake, but after fixing that and running the extension everything works as it should! You can fix it in your spare time and we will merge it right away. Great job and kudos to you for being able to handle it so easily! :1st_place_medal:  I'm glad that the codebase was easy to navigate for you. Thank you very much for your contribution!

**Comment by SharbelOkzan** [comment]
Hii @szymmis, sorry for the late response.
That really drew a smile on my face! I can say I'm fortunate to work with you for my first contribution.
I'll check out the comments on the pr, and hopefully will come back to this repo for a more involved feature when I learn TS, no promises though lol

**Comment by szymmis** [comment]
I've just merged your changes after testing it out again and everything is working fine. I'll make a new update to the Visual Studio Marketplace right away. Thank you very much for your contribution. I hope we will have something more to work on together in the future!
